version: "3"

services:
    minima:
        restart: on-failure
        container_name: minima
        build:
            context: .
        ports:
            - "9001:9001"
            - "9002:9002"
            - "9003:9003"
            - "9004:9004"
            - "9005:9005"
